%% Tutorial for the StochasticRankingES object
% This tutorial shows how to solve the G07 and G12 constrained optimization problems from the paper
% of T.P.Runarsson and X.Yao "Stochastic Ranking for Constrained Evolutionary Optimization", using
% the Stochastic Ranking Evolution Strategy.
%
% See Also: http://cossan.cfd.liv.ac.uk/wiki/index.php/@StochasticRankingES
%
% $Copyright~1993-2012,~University~of~Liverpool,~UK$ $Author: Matteo~Broggi$

%% Define Problem G07

% Define design variables
Ndv = 20;
MembersNames = cell(1, Ndv);
Members = cell(1, Ndv);

for idv =1:Ndv
    MembersNames{idv} = ['dv_' num2str(idv)];
    Members{idv} = opencossan.optimization.ContinuousDesignVariable('value',unifrnd(-10,10),'lowerbound',-10,'upperbound',10);
end

input = opencossan.common.inputs.Input('MembersNames',MembersNames,'Members',Members);

%% Define optimization problem
% Create the objective function
objfun = opencossan.optimization.ObjectiveFunction('Description','objective function',...
    'FunctionHandle',@(x) x(:,1).^2+x(:,2).^2+x(:,1).*x(:,2)-14*x(:,1)-16*x(:,2)+(x(:,3)-10).^2+ ...
    4*(x(:,4)-5).^2+(x(:,5)-3).^2+2*(x(:,6)-1).^2+5*x(:,7).^2 + ...
    7*(x(:,8)-11).^2+2*(x(:,9)-10).^2+(x(:,10)-7).^2+45, ...
    'IsFunction', true, ...
    'InputNames',MembersNames,'OutputNames',{'objective'} , 'Format', 'matrix');

% Add the 8 constraints
con1 = opencossan.optimization.Constraint(...
    'FunctionHandle', @(x) -105 + 4 * x(:,1) + 5 * x(:,2) - 3 * x(:,7) + 9 * x(:,8), ...
    'IsFunction', true, ...
    'InputNames',MembersNames,...
    'OutputNames',{'con1'},...
    'Format', 'matrix');

con2 = opencossan.optimization.Constraint(...
    'FunctionHandle',@(x) 10*x(:,1)-8*x(:,2)-17*x(:,7)+2*x(:,8),...
    'IsFunction', true, ...
    'InputNames',MembersNames,...
    'OutputNames',{'con2'},...
    'Format', 'matrix');

con3 = opencossan.optimization.Constraint('FunctionHandle',@(x) -8*x(:,1)+2*x(:,2)+5*x(:,9)-2*x(:,10)-12, ...
    'IsFunction', true, ...
    'InputNames',MembersNames,...
    'OutputNames',{'con3'},...
    'Format', 'matrix');

con4 = opencossan.optimization.Constraint('FunctionHandle',@(x) 3*(x(:,1)-2).^2+4*(x(:,2)-3).^2+2*x(:,3).^2-7*x(:,4)-120,...
    'IsFunction', true, ...
    'InputNames',MembersNames,...
    'OutputNames',{'con4'},...
    'Format', 'matrix');

con5 = opencossan.optimization.Constraint('FunctionHandle',@(x) 5*x(:,1).^2+8*x(:,2)+(x(:,3)-6).^2-2*x(:,4)-40,...
    'IsFunction', true, ...
    'InputNames',MembersNames,...
    'OutputNames',{'con5'},...
    'Format', 'matrix');

con6 = opencossan.optimization.Constraint('FunctionHandle',@(x) x(:,1).^2+2*(x(:,2)-2).^2-2*x(:,1).*x(:,2)+14*x(:,5)-6*x(:,6),...
    'IsFunction', true, ...
    'InputNames',MembersNames,...
    'OutputNames',{'con6'},...
    'Format', 'matrix');

con7 = opencossan.optimization.Constraint('FunctionHandle',@(x) 0.5*(x(:,1)-8).^2+2*(x(:,2)-4).^2+3*x(:,5).^2-x(:,6)-30,...
    'IsFunction', true, ...
    'InputNames',MembersNames,...
    'OutputNames',{'con7'},...
    'Format', 'matrix');

con8 = opencossan.optimization.Constraint('FunctionHandle',@(x) -3*x(:,1)+6*x(:,2)+12*(x(:,9)-8).^2-7*x(:,10),...
    'IsFunction', true, ...
    'InputNames',MembersNames,...
    'OutputNames',{'con8'},...
    'Format', 'matrix');

%% Define OptimizationProblem
optProb  = opencossan.optimization.OptimizationProblem(...
    'Input',input,'initialsolution',unifrnd(-5,5,1,Ndv), ...
    'objectivefunctions',objfun,...
    'constraints',[con1 con2 con3 con4 con5 con6 con7 con8]);

%% Create optimizer
sr = opencossan.optimization.StochasticRanking('Mu',10,'Lambda',140);

%% Run optimization
optimum = optProb.optimize('optimizer', sr);

%% Check Reference solution
% According to the paper the optimal solution is at 24.306 (the identified solution is at 24.307)

assert((optimum.OptimalObjectiveFunction - 24.306) < 0.5,...
    'OpenCossan:TutorialStochasticRanking',...
    'Solution doesn not match.')