function [b_s, Vrv]=KL_bound(eigval, eigvec, n_eig)

eigval=diag(eigval); eigval=eigval(1:n_eig);
eigvec=eigvec(:,1:n_eig);

Vrv=randn(1,n_eig);
% x stores the random field generated by the K-L representation
b_s=zeros(length(eigvec),1);
for i=1:n_eig
    b_s=b_s+Vrv(i)*eigvec(:,i)*sqrt(eigval(i));
end
