classdef TutorialCredalNetFromDataTest < tutorials.TutorialTest
    properties
        Name = "build_network";
        Variables = ["dis_marg.Disruption.LowerBound", ...
            "dis_marg.Disruption.UpperBound", ...
            "dis_cond.Disruption.LowerBound", ...
            "dis_cond.Disruption.UpperBound"];
        ExpectedValues = {[0.6329; 0.1244], ...
            [0.8756; 0.3671] , ... 
            [0.2089, 0.3714] , ...
            [0.6286, 0.7911]};
        Tolerance = [1e-5, 1e-5, 1e-5, 1e-5];
        PreTest = "";
    end
end