classdef TutorialCredalNetFromDataTest < tutorials.TutorialTest
    properties
        Name = "build_network";
        Variables = ["dis_marg.Disruption.LowerBound", ...
            "dis_marg.Disruption.UpperBound", ...
            "dis_cond.Disruption.LowerBound", ...
            "dis_cond.Disruption.UpperBound"];
        ExpectedValues = {[0.6664; 0.1320], ...
            [0.8680; 0.3336] , ... 
            [0.2089; 0.3714] , ...
            [0.6286; 0.7911]};
        Tolerance = [1e-1, 1e-1, 1e-1, 1e-1 
            ];
        PreTest = "";
    end
end