% dedicated connector for code aster
%
Xobj.Stype = 'aster';
Xobj.Ssolverbinary='/usr/software/SALOME-MECA-2009.1-GPL/aster/outils/as_run';
Xobj.Sexecmd='%Ssolverbinary %Smaininputfile.export ';
Xobj.Caddfiles = [Xobj.Caddfiles,...
    { [Xobj.Smaininputfile '.med'],...
    [Xobj.Smaininputfile '.mess'],...
    [Xobj.Smaininputfile '.base/glob.1.gz'],...
    [Xobj.Smaininputfile '.base/pick.1.gz']...
    }];